# Checker File #
    To check the modules built in the source file

In [1]:
import source
import numpy as np

In [2]:
from tensorflow.keras.datasets import fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

In [3]:
X_train = X_train.reshape(60000,-1)/255.0
X_test = X_test.reshape(10000,-1)/255.0
y_train = source.one_hot_numpy(y_train)
y_test = source.one_hot_numpy(y_test)

In [4]:
arch = [784, 64,10]
activation_sequence =   ['relu', 'softmax']
optimizer = "adam"
learning_rate = 1e-2
loss = "cross_entropy"
initialization = "Xavier"
momentum = 0.95
weight_decay = 0.0001
beta_rms = 0.95
beta_1 = 0.9
beta_2 = 0.99
md2 = source.FeedForwardNeuralNetwork(arch=arch, activation_sequence=activation_sequence, optimizer=optimizer,
                                      learning_rate=learning_rate,weight_decay= weight_decay, loss=loss,initialization=initialization,momentum=momentum,beta_rms=beta_rms,
                                      beta_1=beta_1,beta_2=beta_2)

In [5]:
batch_train = source.Batchloader(X_train, y_train, batch_size=64,shuffle=True)
batch_test = source.Batchloader(X_test, y_test, batch_size=64,shuffle=False)

In [6]:
from sklearn.metrics import precision_score
epochs = 5
#accuracy_train, accuracy_cv, loss_train, loss_cv = np.array([]), np.array([]), np.array([]), np.array([])
for epoch in range(1,epochs+1):
    i = 0
    print(f"Epoch : {epoch}")
    for X_, y_ in batch_train:
        i += 1
        #if i%(600/4) == 0:
        #    print(f" part {int(i//(600/4))}/4 done !!!")
        # One step training
        md2.train_step(X_, y_, epoch)

    train_pred = md2.forward_call(inputs_=X_train)
    test_pred = md2.forward_call(inputs_=X_test)

    loss_train = source.find_loss(y_pred= train_pred, y_true =y_train, loss="cross_entropy")
    loss_test = source.find_loss(y_pred= test_pred, y_true = y_test, loss = "cross_entropy")

    train_pred = md2.forward_call(inputs_=X_train,threshold=True)
    test_pred = md2.forward_call(inputs_=X_test,threshold=True)
    test_pred_l= md2.forward_call(inputs_=X_test,with_logits=True,threshold=True)

    accuracy_train = source.accuracy(train_pred, y_train)
    accuracy_test = source.accuracy(test_pred, y_test)
    accuracy_test_l = source.accuracy(test_pred_l, y_test)
    if epoch%1 == 0:
        print(F"Epoch {epoch} || loss_train : {loss_train} | loss_test : {loss_test} || acc_train : {accuracy_train} | acc_test : {accuracy_test} | acc_test_l : {accuracy_test_l}|")

Epoch : 1
Epoch 1 || loss_train : 0.40085881901698195 | loss_test : 0.44215337337595284 || acc_train : 0.8575166666666667 | acc_test : 0.8447 | acc_test_l : 0.8447|
Epoch : 2


KeyboardInterrupt: 

In [ ]:
train_pred1 = md1.forward_call(inputs_=batch_train, is_batch_both=True)
#train_pred2 = md1.forward_call(inputs_=X_train,threshold=True)

In [ ]:
train_pred1[:5]

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 3.39040216e-175, 0.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        0.0

In [ ]:
A = np.array([1e1000]).astype(np.longdouble)
A / 0.001

array([inf])

In [ ]:
np.sum(train_pred1[:5],axis=1)

array([1., 1., 1., 1., 1.], dtype=float64)

In [ ]:
train_pred2[:5]

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [ ]:
A = np.array([[1,1,3],[4,5,10]])
B = np.sum(A,axis = 0, keepdims=True)

source.softmax(A)

[[2.71828183e+00 2.71828183e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 2.20264658e+04]]
[[   57.31643186   151.13144093 22046.55133173]]
[[4.74258732e-02 1.79862100e-02 9.11051194e-04]
 [9.52574127e-01 9.82013790e-01 9.99088949e-01]]


array([[4.74258732e-02, 1.79862100e-02, 9.11051194e-04],
       [9.52574127e-01, 9.82013790e-01, 9.99088949e-01]])

In [ ]:
arch = [784, 128, 32, 64, 10] 
activation_sequence = ['relu', 'relu', 'sigmoid', 'softmax']
optimizer = "sgd"
learning_rate = 0.001
loss = "cross_entropy"
initialization = "random"
momentum = 0
md1 = source.FeedForwardNeuralNetwork(arch=arch, activation_sequence=activation_sequence, optimizer=optimizer,
                                      learning_rate=learning_rate, loss=loss,initialization=initialization,momentum=momentum)

In [ ]:
import torchvision.transforms as transforms
import torchvision.datasets
import matplotlib.pyplot as plt

# Define the transformation #
transform = transforms.Compose([
    transforms.ToTensor(),  # Converting PIL image to a PyTorch tensor #
])

# Importing the dataset #
train_dataset = torchvision.datasets.MNIST(root = "C:/Users/Joeld/Desktop/IITM/SEM-08/" , train= True, transform=transform, download= True)
# Loading the test data #
test_dataset = torchvision.datasets.MNIST(root = "C:/Users/Joeld/Desktop/IITM/SEM-08/", train= False, transform=transform , download= True)

In [ ]:
train_X = train_dataset.data.numpy()
train_X = train_X.reshape(60000,-1)
train_X = train_X.astype(np.longdouble)
train_y = source.one_hot_numpy(train_dataset.targets.numpy())

test_X = test_dataset.data.numpy()
test_X = test_X.reshape(10000,-1)
test_X = test_X.astype(np.longdouble)
test_y = source.one_hot_numpy(test_dataset.targets.numpy())

In [ ]:
test_y[:5], test_dataset.targets[:5]

(array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64),
 tensor([7, 2, 1, 0, 4]))

In [ ]:
batch_train = source.Batchloader(train_X, train_y, batch_size=5000,shuffle=False)
batch_test = source.Batchloader(test_X, test_y, batch_size=5000,shuffle=False)

In [ ]:
from sklearn.metrics import precision_score
epochs = 10
#accuracy_train, accuracy_cv, loss_train, loss_cv = np.array([]), np.array([]), np.array([]), np.array([])
for epoch in range(1,epochs+1):
    i = 1
    for X_train, y_train in batch_train:
        # One step training
        md1.train_step(X_train, y_train)

    train_pred = md1.forward_call(inputs_=batch_train,is_batch_both=True)
    test_pred = md1.forward_call(inputs_=batch_test,is_batch_both=True)

    accuracy_train = precision_score(y_pred= train_pred, y_true = train_y, average="weighted")
    accuracy_test = precision_score(y_pred= test_pred, y_true = test_y, average="weighted")

    print(F"Epoch {epoch} acc_train : {accuracy_train} acc_test : {accuracy_test}")

KeyboardInterrupt: 

In [ ]:
y_pred = md1.forward_call(batch_test, is_batch_both = True)
y_pred.shape

(10000, 10)

In [ ]:
y_pred[:5]

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [ ]:

test_acc = precision_score(y_pred= y_pred, y_true = test_y, average=None)
test_acc

array([0.10218978, 0.11645299, 0.09763948, 0.09854423, 0.09080717,
       0.08539326, 0.09711846, 0.09655938, 0.10509554, 0.11476664])

In [ ]:
import source
import numpy as np

In [ ]:
Info = [5, 5, 3]
Weights, Biases = source.init_mat(Info, init_scheme="Xavier")

In [ ]:
Weights[0].shape, Weights[1].shape, Weights[2].shape, Biases[0].shape, Biases[1].shape, Biases[2].shape

((20, 10), (20, 20), (2, 20), (20, 1), (20, 1), (2, 1))

In [ ]:
A = np.random.random(size = (8,10))
B = np.array([[0,1],[1,0],[1,0],[0,1],[1,0],[0,1],[0,1],[1,0]])

act = ["tanh","relu","softmax"]
output,preac,postac = source.forward_propagation(input_=A,Weights=Weights,Biases=Biases,activation_sequence=act)

In [ ]:
postac

[array([[0.48083072, 0.57882088, 0.22890125, 0.69667756, 0.48330189,
         0.89149734, 0.05391035, 0.20764917],
        [0.43618723, 0.09015036, 0.08780259, 0.99657987, 0.00278176,
         0.34594457, 0.94818285, 0.18632982],
        [0.25743761, 0.57585937, 0.65681746, 0.75881264, 0.81363467,
         0.54674836, 0.95280503, 0.92658912],
        [0.52929924, 0.55846963, 0.03380309, 0.20248469, 0.61217501,
         0.94150741, 0.89508066, 0.89435619],
        [0.02288824, 0.32877616, 0.57315616, 0.51274884, 0.43955063,
         0.06529684, 0.64015198, 0.43741116],
        [0.67857216, 0.55982527, 0.16730233, 0.09865947, 0.49268503,
         0.34374155, 0.28867639, 0.87369352],
        [0.9309412 , 0.68630334, 0.0883853 , 0.75790219, 0.13193485,
         0.4501492 , 0.66104717, 0.92272033],
        [0.16306415, 0.02396907, 0.83487185, 0.53280878, 0.78235778,
         0.66840801, 0.45208439, 0.29161784],
        [0.07698133, 0.10959643, 0.60176329, 0.48989938, 0.65147018,
         0.

In [ ]:
opti = source.Optimizer(loss="cross_entropy")
gw,gb = opti.backprop_grads(Weights=Weights,Biases=Biases,pre_ac=preac,post_ac=postac,y_true=B,activation_sequence=act)

In [ ]:
Weights[1].shape

(20, 20)

In [ ]:
Info = [2,3,3]
act = ["relu","softmax"]
A = np.array([[1,2]],dtype=np.longdouble)
B = np.array([[0,1,0]],dtype=np.longdouble)
Weights = (np.array([[0.2,0.4],[0.3,0.7],[0.5,0.1]]), np.array([[0.2,0.3,0.5],[0.6,0.7,0.2],[0.1,0.4,0.8]]))
Biases = (np.array([[0.1],[0.2],[0.3]]), np.array([[0.1],[0.2],[0.3]]))
output,preac,postac = source.forward_propagation(input_=A,Weights=Weights,Biases=Biases,activation_sequence=act)
opti = source.Optimizer(loss="cross_entropy")
gw,gb = opti.backprop_grads(Weights=Weights,Biases=Biases,pre_ac=preac,post_ac=postac,y_true=B,activation_sequence=act)
#gw[1].dtype
gw, gb

([array([[ 0.19984302,  0.3451834 ,  0.18167548],
         [-0.55677034, -0.96169423, -0.50615486],
         [ 0.35692732,  0.61651082,  0.32447938]], dtype=float64),
  array([[-0.23490988, -0.46981976],
         [-0.170014  , -0.34002801],
         [ 0.24919027,  0.49838054]], dtype=float64)],
 [array([[ 0.18167548],
         [-0.50615486],
         [ 0.32447938]], dtype=float64),
  array([[-0.23490988],
         [-0.170014  ],
         [ 0.24919027]], dtype=float64)])

In [ ]:
A1 = np.array([1.0,2.0,3.0])

A1 = A1.astype(np.longdouble)
A1

array([1., 2., 3.], dtype=float64)

In [ ]:
opti = source.Optimizer()
batches = source.batchloader(X_data=np.random.random(size=(100,10)),y_data=np.random.random(size=(100,1)),batch_size=32,shuffle=True)
for x,y in batches:
    print(x.shape, y.shape)

(32, 10) (32, 1)
(32, 10) (32, 1)
(32, 10) (32, 1)
(4, 10) (4, 1)


In [ ]:
A1 = np.array([[1,2],[3,4]])
A1

array([[1, 2],
       [3, 4]])

In [ ]:
np.dot(A1[:,1],A1[:,1].T)

20

In [ ]:
np.diag(A1[:])

ValueError: Input must be 1- or 2-d.

In [ ]:
num_rows, num_columns = A1.shape

# Create a 3D array to hold the stacked diagonal matrices
stacked_diagonal_matrices = np.zeros((num_rows, num_rows,num_columns,))

# Use advanced indexing to fill the diagonals
stacked_diagonal_matrices[np.arange(num_rows), np.arange(num_rows), :] = A1.T

stacked_diagonal_matrices

array([[[1., 3.],
        [0., 0.]],

       [[0., 0.],
        [2., 4.]]])

In [ ]:
import source
import numpy as np
input_ = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
grads = np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]])
Final_grads = source.diff_softmax(input_,grads)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,5)->(3,5,newaxis) (3,3)->(3,3) 

In [ ]:
Final_grads.shape

(3, 5)

In [ ]:
A1.shape[] == A1.shape[[0,1]]

TypeError: tuple indices must be integers or slices, not list

In [ ]:
#A1 = np.random.random((10,5))
A1 = np.array([[1,2],[3,4]])
#np.einsum("ij,kj->ikj",A1,A1)[:,:,1]
#np.expand_dims(A1,axis=1)
b1 = np.array([[1],[2]])

A1/b1

array([[1. , 2. ],
       [1.5, 2. ]])

In [ ]:
import source
import numpy as np
output_ = np.array([[0.1,0.3],[0.5,0.3],[0.4,0.4]])
grads = np.array([[0,0],[-1/0.4,0],[0,-1/0.4]])
Diag_mat, Cross_mat, Diff_mat, Expanded_grads_postact, Final_grads = source.diff_softmax(output_,grads)

In [ ]:
(np.einsum("ij,kj->ikj",A1,A1)*np.expand_dims(np.array([[1,2],[3,4]]),axis=1))[:,:,1]

array([[ 8, 16],
       [32, 64]])

In [ ]:
np.expand_dims(np.array([[1,2],[3,4]]),axis=1)[:,0,:]

array([[1, 2],
       [3, 4]])

In [ ]:
np.expand_dims(A1,axis=2)[:,:,0]

array([[1, 2],
       [3, 4]])

In [ ]:
Diag_mat = np.einsum("jk,ij->ijk", A1, np.eye(A1.shape[0]))[:,:,]
Diag_mat

array([[[1., 2.],
        [0., 0.]],

       [[0., 0.],
        [3., 4.]]])